<?php
	//start session varriable
   session_start();
   //access the connection variables
   require '../include/Connection_DB.php';
   $db = new Connection_DB(); 
   $con = $db->connect();

   

   	//allow the code to run online if the submit report button has been clicked on 
	if (isset($_POST['ReportSubmit'])) {
		#code...

		$typeOfExport = mysqli_real_escape_string($con, $_POST['type_format']);
		$typeOfReport = mysqli_real_escape_string($con, $_POST['reportType']);
		$account_numberQuerry = mysqli_real_escape_string($con, $_POST['account_numb']);
		$selectedDate = mysqli_real_escape_string($con, $_POST['tranStart_date']);
		$endDate = mysqli_real_escape_string($con, $_POST['end_date']);

		if ($typeOfExport == 'pdf' || $typeOfExport == 'PDF') {
			# code...
			//require the FPDF class to generate the pdf.
			require '../pdfGen/fpdf.php';
			if ($typeOfReport == 'list' || $typeOfExport == 'List') {
				# code...

				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Clients List Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(20 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				$pdf->Cell(50 ,5,'Account Number',1,0);
				$pdf->Cell(50 ,5,'Account Name',1,0);
				$pdf->Cell(60 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(60,5,'Date Account Added',1,0);
				$pdf->Cell(34,5,'Added By',1,1);


				//this will go in a while loop but for now
				// $getAllClients = "SELECT a.account_number, a.account_name, a.balance, t.* FROM account as a, transactions as t WHERE a.account_number = t.sender_acc_no  ";
				$getAllClients = "SELECT * FROM ACCOUNT ORDER BY  date_created ASC";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$account_number = $getClientsRows['account_number'];
						$account_holder = $getClientsRows['account_name'];
						$balance = $getClientsRows['balance'];

						$pdf->Cell(50,5,''.$account_number.'',1,0);
						$pdf->Cell(50,5,''.$account_holder.'',1,0);
						$pdf->Cell(60,5,'ZWK '.number_format((float)$balance).'',1,0,'L');
						$pdf->Cell(60,5,''.$getClientsRows['date_created'],1,0,'L');
						$pdf->Cell(34,5,''.ucfirst($getClientsRows['admin_username']),1,1,'L');//end of line
					}
				}


				$pdf->SetFont('Arial','',12);

				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();


			} elseif ($typeOfReport == 'single' || $typeOfExport == 'single') {
				# code...


				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A4');
				//add new page
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'Report for '.$account_numberQuerry,0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number = '$account_Querry'";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance = $getDetailsRows['balance'];
						$account_holder = $getDetailsRows['account_name'];
						$pdf->SetFont('Arial','B',14);

						$pdf->Cell(130, 5, 'Account Holder Name: '.$getDetailsRows['account_name'].'',0,1);

						$pdf->SetFont('Arial','',12);
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,1);


					}
				}
				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				$pdf->Cell(65 ,5,'Transaction Details',1,0);
				$pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,0);
				$pdf->Cell(34,5,'Trans Date',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM transactions WHERE  receiver_acc_no = '$account_numberQuerry' ";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['sender_acc_no'];
						$rec = $getClientsRows['receiver_acc_no'];

						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						if ($trans == $account_numberQuerry) {
							# code...
							$pdf->Cell(65,5,'Sent to '.$rec.'',1,0);

						} else {
							$pdf->Cell(65,5,'Recivered from '.$trans.'',1,0);
						}
						
						$pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
						$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,0,'L');
						$pdf->Cell(34,5,''.$getClientsRows['trans_date'],1,1,'L');//end of line
						
					}
				}


				$pdf->SetFont('Arial','',12);

				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();


			} elseif ($typeOfReport == 'single_date') {
				# code...
				

				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A4');
				//add new page
					$pdf->SetTitle('Single Client Report for Account '.$account_numberQuerry.' Between '.$selectedDate.' And '.$endDate);
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'Report for '.$account_numberQuerry,0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(32 ,5,'Date Generated:',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number = '$account_numberQuerry'";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance = $getDetailsRows['balance'];
						$account_holder = $getDetailsRows['account_name'];
						$pdf->SetFont('Arial','B',14);

						$pdf->Cell(130, 5, 'Account Holder Name: '.$getDetailsRows['account_name'].'',0,1);

						$pdf->SetFont('Arial','',12);
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,1);

					}
				}
				$pdf->SetFont('Arial','B',14);
				$pdf ->Cell(100, 5, 'Transaction from '.$selectedDate.' to '.$endDate.'',0,0);
				$pdf->SetFont('Arial','',12);

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				$pdf->Cell(65 ,5,'Transaction Details',1,0);
				$pdf->Cell(50 ,5,'Date of trans',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,0);
				 $pdf->Cell(34,5,'Date',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM transactions WHERE sender_acc_no = '$account_numberQuerry' AND receiver_acc_no = '$account_numberQuerry' ";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['sender_acc_no'];
						$rec = $getClientsRows['receiver_acc_no'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						if ($trans == $account_numberQuerry) {
							# code...
							$pdf->Cell(65,5,'Sent to '.$rec.'',1,0);

						} else {
							$pdf->Cell(65,5,'Recivered from '.$trans.'',1,0);
						}
						
						$pdf->Cell(50,5,' '.$date.'',1,0);
						$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,0,'L');
						$pdf->Cell(34,5,''.$getClientsRows['trans_date'],1,1,'L');//end of line					
					}
				}else {
					$pdf -> Cell(149,5,'No Record',1,1,'C');
				}


				$pdf->SetFont('Arial','',12);



				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();


			} elseif ($typeOfReport == 'list_trans') {
				# code...



				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('All clients transactions');
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Transactions Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance .= $getDetailsRows['balance'];
						$account_holder .= $getDetailsRows['account_name'];
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,0);

					}
				}
				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				// $pdf->Cell(30,5,'Acc Name',1,0);
				$pdf->Cell(30,5,'Sender',1,0);
				$pdf->Cell(30,5,'Receiver',1,0);
				$pdf->Cell(100 ,5,'Transaction Details',1,0);
				$pdf->Cell(30,5,'Date',1,0);
				// $pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM transactions";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['sender_acc_no'];
						$rec = $getClientsRows['receiver_acc_no'];
						$remarks = $getClientsRows['remark'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						
							# code...
							// $pdf->Cell(30,5,$account_holder,1,0);
						

						
							$pdf->Cell(30,5,''.$trans.'',1,0);
							$pdf->Cell(30,5,''.$rec.'',1,0);
							$pdf->Cell(100,5,$remarks,1,0);
					
							$pdf->Cell(30,5,$date,1,0);
							// $pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
							$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,1,'R');//end of line
						
					}
				} else {
					// $pdf ->Cell(300,5,'No Data',1,1);
				}


				$pdf->SetFont('Arial','',12);
				// $pdf->Footer();
				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();

			} elseif ($typeOfReport == 'list_date') {
				# code...



				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('Clients Transactions Between '.$selectedDate.' And '.$endDate);
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Transactions Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance .= $getDetailsRows['balance'];
						$account_holder .= $getDetailsRows['account_name'];
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,0);

					}
				}
				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				// $pdf->Cell(30,5,'Acc Name',1,0);
				$pdf->Cell(30,5,'Sender',1,0);
				$pdf->Cell(30,5,'Receiver',1,0);
				$pdf->Cell(100 ,5,'Transaction Details',1,0);
				$pdf->Cell(30,5,'Date',1,0);
				// $pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM transactions WHERE trans_date BETWEEN '$selectedDate' AND '$endDate' ";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['sender_acc_no'];
						$rec = $getClientsRows['receiver_acc_no'];
						$remarks = $getClientsRows['remark'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						
							# code...
							// $pdf->Cell(30,5,$account_holder,1,0);
						

						
							$pdf->Cell(30,5,''.$trans.'',1,0);
							$pdf->Cell(30,5,''.$rec.'',1,0);
							$pdf->Cell(100,5,$remarks,1,0);
					
							$pdf->Cell(30,5,$date,1,0);
							// $pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
							$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,1,'R');//end of line
						
					}
				} else {
					// $pdf ->Cell(300,5,'No Data',1,1);
				}


				$pdf->SetFont('Arial','',12);
				// $pdf->Footer();
				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();


			} elseif ($typeOfReport == 'created_on') {
				# code...
				

				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('Clients Created On');
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Clients Between '.$selectedDate.' AND '.$endDate.'',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(20 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line

				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				$pdf->Cell(50 ,5,'Account Number',1,0);
				$pdf->Cell(50 ,5,'Account Name',1,0);
				$pdf->Cell(60 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(60,5,'Date Account Added',1,0);
				$pdf->Cell(34,5,'Added By',1,1);


				//this will go in a while loop but for now
				// $getAllClients = "SELECT a.account_number, a.account_name, a.balance, t.* FROM account as a, transactions as t WHERE a.account_number = t.sender_acc_no  ";
				$getAllClients = "SELECT * FROM ACCOUNT WHERE  date_created BETWEEN  '$selectedDate' AND '$endDate'";

				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);
				// $pdf->Cell(130,5,''.$selectedDate.' '.$endDate,1,1,'L');
				if ($getClientsnumb > 0) {
					# code...
					// $pdf->Cell(130,5,''.$selectedDate.' '.$endDate,1,1,'L');
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$account_number = $getClientsRows['account_number'];
						$account_holder = $getClientsRows['account_name'];
						$balance = $getClientsRows['balance'];

						$pdf->Cell(50,5,''.$account_number.'',1,0);
						$pdf->Cell(50,5,''.$account_holder.'',1,0);
						$pdf->Cell(60,5,'ZWK '.number_format((float)$balance).'',1,0,'L');
						$pdf->Cell(60,5,''.$getClientsRows['date_created'],1,0,'L');
						$pdf->Cell(34,5,''.ucfirst($getClientsRows['admin_username']),1,1,'L');//end of line
					}
				}else {
					// $pdf->Cell(130,5,''.$selectedDate.' '.$endDate,1,1,'L');
					echo "".mysqli_error($con);
				}


				$pdf->SetFont('Arial','',12);

				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output('','');
			} elseif($typeOfReport == 'zesco_bills'){



				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('All clients transactions');
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Transactions Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance .= $getDetailsRows['balance'];
						$account_holder .= $getDetailsRows['account_name'];
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,0);

					}
				}
				

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				// $pdf->Cell(30,5,'Acc Name',1,0);
				$pdf->Cell(100,5,'Clients Account Number',1,0);
				// $pdf->Cell(30,5,'Receiver',1,0);
				$pdf->Cell(100 ,5,'Transaction Details',1,0);
				$pdf->Cell(30,5,'Date',1,0);
				// $pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM utility_transactions";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['client_acc_no'];
						// $rec = $getClientsRows['receiver_acc_no'];
						$remarks = $getClientsRows['remark'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						
							# code...
							// $pdf->Cell(30,5,$account_holder,1,0);
						

						
							$pdf->Cell(100,5,''.$trans.'',1,0);
							// $pdf->Cell(30,5,''.$rec.'',1,0);
							$pdf->Cell(100,5,$remarks,1,0);
					
							$pdf->Cell(30,5,$date,1,0);
							// $pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
							$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,1,'R');//end of line
						
					}
				} else {
					// $pdf ->Cell(300,5,'No Data',1,1);
				}


				$pdf->SetFont('Arial','',12);
				// $pdf->Footer();
				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();


			}elseif($typeOfReport == 'single_zesco_bills'){


				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('All clients transactions');
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Transactions Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line
				$pdf->Cell(59 ,5,'Report for '.$account_numberQuerry,0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance .= $getDetailsRows['balance'];
						$account_holder .= $getDetailsRows['account_name'];
						// $pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,0);

				
			
						$pdf->Cell(130, 5, 'Account Holder Name: '.$getDetailsRows['account_name'].'',0,1);
						$pdf->SetFont('Arial','',12);
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,1);

					}
				}
				$pdf->SetFont('Arial','B',14);
				// $pdf ->Cell(100, 5, 'Transaction from '.$selectedDate.' to '.$endDate.'',0,0);

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				// $pdf->Cell(30,5,'Acc Name',1,0);
				$pdf->Cell(100,5,'Clients Account Number',1,0);
				// $pdf->Cell(30,5,'Receiver',1,0);
				$pdf->Cell(100 ,5,'Transaction Details',1,0);
				$pdf->Cell(30,5,'Date',1,0);
				// $pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM utility_transactions WHERE client_acc_no = '$account_numberQuerry'";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['client_acc_no'];
						// $rec = $getClientsRows['receiver_acc_no'];
						$remarks = $getClientsRows['remark'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						
							# code...
							// $pdf->Cell(30,5,$account_holder,1,0);
						

						
							$pdf->Cell(100,5,''.$trans.'',1,0);
							// $pdf->Cell(30,5,''.$rec.'',1,0);
							$pdf->Cell(100,5,$remarks,1,0);
					
							$pdf->Cell(30,5,$date,1,0);
							// $pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
							$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,1,'R');//end of line
						
					}
				} else {
					// $pdf ->Cell(300,5,'No Data',1,1);
				}


				$pdf->SetFont('Arial','',12);
				// $pdf->Footer();
				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();



			}elseif($typeOfReport == 'single_zesco_bills_dates'){

				
				//A4 width : 219mm
				//default margin : 10mm each side
				//writable horizontal : 219-(10*2)=189mm

				//create pdf object
				$pdf = new FPDF('P','mm','A3');
				//add new page
				$pdf->SetTitle('All clients transactions');
				$pdf->AddPage();
			

				//set font to arial, bold, 14pt
				$pdf->SetFont('Arial','B',14);

				//Cell(width , height , text , border , end line , [align] )

				$pdf->Cell(130 ,5,'Remote Banking System',0,0);
				$pdf->Cell(59 ,5,'All Transactions Report',0,1);//end of line

				//set font to arial, regular, 12pt
				$pdf->SetFont('Arial','',12);

				$pdf->Cell(130 ,5,'Generated By: '.ucfirst($_SESSION['login_user']),0,0);
				$pdf->Cell(59 ,5,'',0,1);//end of line
				$pdf->Cell(59 ,5,'Report for '.$account_numberQuerry,0,1);//end of line

				$currentDate = date('d/m/Y');
				$pdf->Cell(130 ,5,'[Kabwe,Zambia]',0,0);
				$pdf->Cell(25 ,5,'Date',0,0);
				$pdf->Cell(34 ,5,''.$currentDate.'',0,1);//end of line
				//this will go in a while loop but for now
				// $pdf -> Cell(25 ,5,' ',0,0);
				$acc_balance = "";
				$account_holder = "";
				$getDetails= "SELECT * FROM account WHERE account_number";
				$getDetailsQuery = mysqli_query($con, $getDetails);
				$getDetailsNumb = mysqli_num_rows($getDetailsQuery);

				if ($getDetailsNumb > 0) {

					# code...

					while ($getDetailsRows = mysqli_fetch_assoc($getDetailsQuery)) {
						# code...
						$acc_balance .= $getDetailsRows['balance'];
						$account_holder .= $getDetailsRows['account_name'];
						// $pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,0);

				
			
						$pdf->Cell(130, 5, 'Account Holder Name: '.$getDetailsRows['account_name'].'',0,1);
						$pdf->SetFont('Arial','',12);
						$pdf->Cell(130 ,5,'Balance ZWK '.number_format((float)$acc_balance).'',0,1);

					}
				}
				$pdf->SetFont('Arial','B',14);
				$pdf ->Cell(100, 5, 'Transaction from '.$selectedDate.' to '.$endDate.'',0,0);

				//make a dummy empty cell as a vertical spacer
				$pdf->Cell(189 ,10,'',0,1);//end of line

				
				//invoice contents
				$pdf->SetFont('Arial','B',12);

				// $pdf->Cell(50 ,5,'Account Number',1,0);
				// $pdf->Cell(50, 5,'',1,0);
				// $pdf->Cell(30,5,'Acc Name',1,0);
				$pdf->Cell(100,5,'Clients Account Number',1,0);
				// $pdf->Cell(30,5,'Receiver',1,0);
				$pdf->Cell(100 ,5,'Transaction Details',1,0);
				$pdf->Cell(30,5,'Date',1,0);
				// $pdf->Cell(50 ,5,'Current Balance',1,0);//end of line
				$pdf->Cell(34,5,'Transactions',1,1);


				//this will go in a while loop but for now
				$getAllClients = "SELECT * FROM utility_transactions WHERE  trans_date BETWEEN '$selectedDate' AND '$endDate'";
				$getClientsQuery = mysqli_query($con, $getAllClients);
				$getClientsnumb = mysqli_num_rows($getClientsQuery);

				if ($getClientsnumb > 0) {
					# code...
				
					while ($getClientsRows = mysqli_fetch_assoc($getClientsQuery)) {
						# code...
						$transactions_amount = $getClientsRows['transaction_amount'];
						$trans = $getClientsRows['client_acc_no'];
						// $rec = $getClientsRows['receiver_acc_no'];
						$remarks = $getClientsRows['remark'];
						$date = $getClientsRows['trans_date'];
						
						// $pdf->Cell(50,5,''.$account_number.'',1,0);
						
							# code...
							// $pdf->Cell(30,5,$account_holder,1,0);
						

						
							$pdf->Cell(100,5,''.$trans.'',1,0);
							// $pdf->Cell(30,5,''.$rec.'',1,0);
							$pdf->Cell(100,5,$remarks,1,0);
					
							$pdf->Cell(30,5,$date,1,0);
							// $pdf->Cell(50,5,'ZWK '.number_format((float)$acc_balance).'',1,0);
							$pdf->Cell(34,5,'ZWK '.number_format((float)$transactions_amount),1,1,'R');//end of line
						
					}
				} else {
					// $pdf ->Cell(300,5,'No Data',1,1);
				}


				$pdf->SetFont('Arial','',12);
				// $pdf->Footer();
				//Numbers are right-aligned so we give 'R' after new line parameter
				$pdf->Output();
			}


		}
		
	}

?>